### ISSUE TITLE
data/clients.txt

### ISSUE THREAD

**Issue by GenryMorgan777** [Pechenyice/vkAnsweringBot#1]
Error: ENOENT: no such file or directory, open 'data/clients.txt'
    at Object.fs.openSync (fs.js:646:18)
    at Object.fs.readFileSync (fs.js:551:33)
    at Object.<anonymous> (/home/ubuntu/vkAnsweringBot/main.js:17:18)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Function.Module.runMain (module.js:693:10)
    at startup (bootstrap_node.js:188:16)

**Comment by Pechenyice** [comment]
ye, i know, this bot is 2.5 years old.
I use fs.readfile so u should create files (in directory data/):
‘appId.txt’ — id of your vk app
‘clients.txt’ — enter your clients ids there
‘messageToken.txt’ — your token with message access (look for oauth link in index.htm)
‘modes.json’ — leave it empty, i think all will be ok
‘token.txt’ — leave it empty

and use ‘main — копия.js’ because i am lazy :(

  
>Среда, 9 сентября 2020, 14:39 +03:00 от GenryMorgan777 <notifications@github.com>:
> 
> 
>Error: ENOENT: no such file or directory, open 'data/clients.txt'
>at Object.fs.openSync (fs.js:646:18)
>at Object.fs.readFileSync (fs.js:551:33)
>at Object. (/home/ubuntu/vkAnsweringBot/main.js:17:18)
>at Module._compile (module.js:652:30)
>at Object.Module._extensions..js (module.js:663:10)
>at Module.load (module.js:565:32)
>at tryModuleLoad (module.js:505:12)
>at Function.Module._load (module.js:497:3)
>at Function.Module.runMain (module.js:693:10)
>at startup (bootstrap_node.js:188:16)
>—
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly,  view it on GitHub , or  unsubscribe . 
 
 
--
Герман Исхаков
